STATE_EXECUTED = 'EXECUTED'
KEY_STATE = 'state'
KEY_DATE = 'date'
KEY_DATE_OBJ = 'date'
KEY_ID = 'id'
KEY_DESCRIPTION = 'description'
KEY_TO = 'to'
KEY_FROM = 'from'
KEY_SUM = 'from'
KEY_OPERATION_AMOUNT = 'operationAmount'
KEY_AMOUNT = 'amount'
KEY_CURRENCY = 'currency'
KEY_NAME = 'name'
KEY_CODE = 'code'

